include:
- ./func/*
kind: ArchiveUploadSpec
name: func-ao5s

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: fn-put-tax-residence-e52f763b-04b6-40fa-a895-c5965fc30fdb
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: env-put-tax-residence
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-ao5s
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-18T17:27:15Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: fn-put-tax-residence
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: env-put-tax-residence
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.update_external_fiscal_tax
    packageref:
      name: fn-put-tax-residence-e52f763b-04b6-40fa-a895-c5965fc30fdb
      namespace: default
  requestsPerPod: 10000
  resources: {}
