apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: route-put-tax-residence
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: fn-put-tax-residence
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /onboarding/external_fiscal_tax_confirmation
    tls: ""
  method: ""
  methods:
  - PUT
  prefix: ""
  relativeurl: /onboarding/external_fiscal_tax_confirmation
